add_outcome MVP
Aarhus-Psychiatry-Research/timeseries-flattener pull request #9
Opened 2022-03-25 09:53 UTC by martbern

Minimum viable product, simply for `add_outcome`! Let's see what you guys think ;-)

Primarily thinking about the API, but most of the methods implemented for `add_outcome` are near-mature as well.

2022-03-28 13:31 UTC, HLasse requested changes
Rigtig fint første bud! Der bliver iterereret rigtig meget - jeg er bange for det godt kunne gå hen og blive sløjt med så mange `.apply` kald. Lægger hovedet i blød om vi kan gøre noget andet. 

API'en virker fornuftig. Som det er nu skal der også skrives noget kode så det er nemt at danne en `prediction_df` så man kan loope over alle de features man gerne vil skabe. Alternativt skal den tage `prediction_df` i __init__ som et stort sparse dataset hvor man giver `add_predictor` et kolonnenavn i stedet. Usikker på hvad der er bedst for hastighed

2022-03-28 13:31 UTC, HLasse commented on src/timeseriesflattener/flattened_dataset.py
> +) -> Boolean:
```suggestion
) -> bool:
```

2022-03-28 13:31 UTC, HLasse commented on src/timeseriesflattener/flattened_dataset.py
> +            val_dict (Dict[str, List[Dict[datetime, int]]]): A dict containing the timestamps and vals for the events.
```suggestion
            val_dict (Dict[str, List[List[datetime, int]]]): A dict containing the timestamps and vals for the events.
```

2022-03-28 13:31 UTC, HLasse commented on src/timeseriesflattener/flattened_dataset.py
> +                    list(x) for x in zip(x[timestamp_colname], x[values_colname])
```suggestion
                lambda row: [
                    list(x) for x in zip(row[timestamp_colname], row[values_colname])
```

2022-03-28 13:31 UTC, HLasse commented on src/timeseriesflattener/flattened_dataset.py
> +            val_dict (Dict[str, List[Dict[datetime, int]]]): A dict containing the timestamps and vals for the events.
Samme som kommentar ved linje 160

2022-03-28 13:31 UTC, HLasse commented on tests/add_outcome_tests.py
> +    run_tests_from_df_strings(prediction_times_str, event_times_str, [1])
Lidt weird at konstruere dataframes fra strings. Enten lav dem som dict (`pd.DataFrame({"dw_ek_borger" : [1, 2, 3], "timestamp" : [2,3,4], ...})` eller læs fra csv

2022-03-28 13:31 UTC, HLasse commented on src/timeseriesflattener/flattened_dataset.py
> +        return True
```suggestion
        raise NotImplementedError
```

2022-03-29 08:53 UTC, martbern commented
> Rigtig fint første bud! Der bliver iterereret rigtig meget - jeg er bange for det godt kunne gå hen og blive sløjt med så mange `.apply` kald. Lægger hovedet i blød om vi kan gøre noget andet.

Helt enig ift. iteration! Men vil `.apply` ikke parallellisere over rows?

> API'en virker fornuftig. Som det er nu skal der også skrives noget kode så det er nemt at danne en `prediction_df` så man kan loope over alle de features man gerne vil skabe. Alternativt skal den tage `prediction_df` i **init** som et stort sparse dataset hvor man giver `add_predictor` et kolonnenavn i stedet. Usikker på hvad der er bedst for hastighed

Yeps, det er den jeg kalder `self.df` – et mere deskriptivt navn er nok bedre, bruger `prediction_df` indtil videre 👍

2022-03-29 08:56 UTC, martbern commented on tests/add_outcome_tests.py
> +    run_tests_from_df_strings(prediction_times_str, event_times_str, [1])
Hmm, her er jeg uenig ;-)

Synes det er væsentligt nemmere at læse ovenstående, og det gør det nemmere at gennemskue, hvad formålet med testen er. Ligesom en tribble!

2022-03-29 10:41 UTC, merged